# Deploys a new Namespace for the MinIO Pod
apiVersion: v1
kind: Namespace
metadata:
  name: minio-dev # Change this value if you want a different namespace name
  labels:
    name: minio-dev # Change this value to match metadata.name
---
# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
#
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio-dev # Change this value to match the namespace metadata.name
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args:
    - minio server /data0 /data1 /data2 /data3 --console-address :9090
    volumeMounts:
    - mountPath: /data0
      name: loop0
    - mountPath: /data1
      name: loop1
    - mountPath: /data2
      name: loop2
    - mountPath: /data3
      name: loop3
  volumes:
  - name: loop0
    hostPath:
      path: /mnt/extra/loop-devs/loop0
      type: DirectoryOrCreate
  - name: loop1
    hostPath:
      path: /mnt/extra/loop-devs/loop1
      type: DirectoryOrCreate
  - name: loop2
    hostPath:
      path: /mnt/extra/loop-devs/loop2
      type: DirectoryOrCreate
  - name: loop3
    hostPath:
      path: /mnt/extra/loop-devs/loop3
      type: DirectoryOrCreate